### ISSUE TITLE
Grub: /boot/grub/x86_64-efi/normal.mod not found

### ISSUE THREAD

**Issue by midenok** [midenok/stuff-linux#20]
https://help.ubuntu.com/community/Grub2/Troubleshooting

1. Run`set`, it says **prefix** where it searches for `normal.mod`;
2. Run `ls` for that `prefix` value, check the contents of partition, find correct partition;
3. Set correct **prefix**;
4. Run `insmod /boot/grub/x86_64-efi/normal.mod`;
5. Run `normal`.

**Comment by midenok** [comment]
Cleanup EFI partition for all needless `grub` files as grub anyway can't read anything from FAT. reFind loads `grubx64.efi` and that's only needed from EFI partition.

**Comment by midenok** [comment]
Trouble with DELL: it find `boot/grub/i386-pc/normal.mod` instead of `x86_64-efi` though `grub-install` done 64-bit target (in efi) mode. That's because DELL was in legacy mode and loaded boot sector, not efi partition. Boot sector is prepared for i386 only (I guess).

**Comment by Thilagu** [comment]
![16156352474842244254336516081727](https://user-images.githubusercontent.com/80579666/111028684-2637ab80-841e-11eb-9e12-b01ef56e99a8.jpg)
Hi im Thilagu. i have kali linux version 2020.4in my laptop. Today i Swtich it on. I got a error: file '/boot/grub/x86_64-efi/normal.mod' not found. I did all command what i know... But still not fix so please help me. And i cannot open Windows os also!

**Comment by yugendhra** [comment]
Did you find a solution thilagu?? 
Please post the solution
Thanks in advance

**Comment by Zeioth** [comment]
> ![16156352474842244254336516081727](https://user-images.githubusercontent.com/80579666/111028684-2637ab80-841e-11eb-9e12-b01ef56e99a8.jpg) Hi im Thilagu. i have kali linux version 2020.4in my laptop. Today i Swtich it on. I got a error: file '/boot/grub/x86_64-efi/normal.mod' not found. I did all command what i know... But still not fix so please help me. And i cannot open Windows os also!

This issue happens to me a 25% of the times I reboot. I wonder why.

**Comment by buriihenry** [comment]
If the above guide doesn't work for you, get a Windows installation media(USB flash drive or CD) and start the windows installation up to a point where you delete the partitions created during Linux/ Ubuntu installation. Delete all the partitions and eject the flash drive/CD and start the Linux installation again. It worked for me.
